---
aap_hub_certified_url: 'https://console.redhat.com/api/automation-hub/content/published/'
aap_hub_certified_auth_url: 'https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token'
aap_hub_validated_url: 'https://console.redhat.com/api/automation-hub/content/validated/'
aap_hub_validated_auth_url: 'https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token'

# Force inventories to use empty dict for variables instead of omit
aap_configuration_enforce_defaults: true
...
