---
# https://console.redhat.com/ansible/automation-hub/repo/validated/infra/aap_configuration/content/role/controller_credentials/

controller_credentials:
  - name: Github
    description: Github access to clone repositories
    organization: Lab
    credential_type: Source Control
    inputs:
      username: "{{ git_username }}"
      password: "{{ git_password }}"
      ssh_key_data: "{{ git_ssh_private_key }}"
      ssh_key_unlock: "{{ git_ssh_key_passphrase }}"

  - name: "Ansible Vault All"
    credential_type: Vault
    description: Vault password for all environments
    organization: Lab
    inputs:
      vault_password: "{{ aap_vault_password_all }}"
      vault_id: 'all'
    
  - name: "Ansible Vault {{ aap_env }}"
    credential_type: Vault
    description: "Vault password for {{ aap_env }} environment"
    organization: Lab
    inputs:
      vault_password: "{{ aap_vault_password }}"
      vault_id: "{{ aap_env }}"
    
  - name: "aap-{{ aap_env }}"
    description: AAP for {{ aap_env }} environment
    credential_type: Red Hat Ansible Automation Platform
    organization: Lab
    inputs:
      host: "{{ aap_hostname }}"
      username: "{{ aap_username }}"
      password: "{{ aap_password }}"
      verify_ssl: "{{ aap_validate_certs }}"

  - name: Red Hat Automation Hub Certified
    description: Red Hat Automation Hub Certified Credential
    organization: Lab
    credential_type: Ansible Galaxy/Automation Hub API Token
    inputs:
      url: "{{ aap_hub_certified_url }}"
      auth_url: "{{ aap_hub_certified_auth_url }}"
      token: "{{ aap_hub_certified_token }}"

  - name: Red Hat Automation Hub Validated
    description: Red Hat Automation Hub Validated Credential
    organization: Lab
    credential_type: Ansible Galaxy/Automation Hub API Token
    inputs:
      url: "{{ aap_hub_validated_url }}"
      auth_url: "{{ aap_hub_validated_auth_url }}"
      token: "{{ aap_hub_validated_token }}"

...
