---
# https://console.redhat.com/ansible/automation-hub/repo/validated/infra/aap_configuration/content/role/controller_schedules

controller_schedules:
  - name: Config as Code from main
    description: Config as Code applied from main branch
    unified_job_template: Config as Code
    rrule: "DTSTART;TZID=America/Chicago:20251124T000000 RRULE:FREQ=DAILY;INTERVAL=1;WKST=MO;BYDAY=MO,TU,WE,TH,FR;BYHOUR=6;BYMINUTE=0;BYSECOND=0"
    scm_branch: 'main'
    extra_data:
      git_branch: 'main'
      aap_env: "{{ aap_env }}"
...
